export const INCREMENT_SOME_ATTRIBUTE = 'INCREMENT_SOME_ATTRIBUTE';
export type INCREMENT_SOME_ATTRIBUTE = typeof INCREMENT_SOME_ATTRIBUTE;

export const DECREMENT_SOME_ATTRIBUTE = 'DECREMENT_SOME_ATTRIBUTE';
export type DECREMENT_SOME_ATTRIBUTE = typeof DECREMENT_SOME_ATTRIBUTE;

